description: "Slimefun is a Paper plugin that simulates a modpack-like atmosphere by adding over 500 new items and recipes to your Minecraft Server."
java: "25"
paper: "1.16.* - 26.1.*"
gradle_plugin: "1.8.2.1"
