commit_message: New translations for %file_name% from Crowdin
files:
  - source: /src/main/resources/languages/en/*.yml
    translation: /src/main/resources/languages/%two_letters_code%/%original_file_name%
