paperApiVersion=26.1.2.build.+
shadowVersion=9.3.2
githubGradleVersion=1.8.2.1
runPaperVersion=3.0.2

slimefunAddons=Slimefun5/ExtraGear,Slimefun5/LuckyBlocks,Slimefun5/ChestTerminal,Slimefun5/SlimefunAdvancements,Slimefun5/ExoticGarden,Slimefun5/MissileWarfare,Slimefun5/LiteXpansion,Slimefun5/FluffyMachines,Slimefun5/InfinityExpansion,Slimefun5/DynaTech,Slimefun5/SensibleToolbox,Slimefun5/Galactifun,Slimefun5/SlimeTinker
