paperApiVersion=26.1.2.build.+
shadowVersion=9.3.2
githubGradleVersion=1.8.4.1
runPaperVersion=3.0.2

slimefunAddons=Slimefun5/ExtraGear@experimental,Slimefun5/LuckyBlocks@experimental,Slimefun5/ChestTerminal@experimental,Slimefun5/SlimefunAdvancements@experimental,Slimefun5/ExoticGarden@experimental,Slimefun5/MissileWarfare@experimental,Slimefun5/LiteXpansion@experimental,Slimefun5/FluffyMachines@experimental,Slimefun5/InfinityExpansion@experimental,Slimefun5/DynaTech@experimental,Slimefun5/SensibleToolbox@experimental,Slimefun5/Galactifun@experimental,Slimefun5/SlimeTinker@experimental,Slimefun5/SoulJars@experimental
