name: Java CI

on:
  push:
    branches:
    - stable
    paths:
    - 'src/**'
    - 'build.gradle.kts'
    - 'settings.gradle.kts'
  pull_request:
    paths:
    - '.github/workflows/**'
    - 'src/**'
    - 'build.gradle.kts'
    - 'settings.gradle.kts'
    - 'CHANGELOG.md'

permissions:
  contents: read

jobs:
  build:

    name: Gradle build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'adopt'
        java-version: '21'
        java-package: jdk
        architecture: x64

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v4
    - run: chmod +x ./gradlew
    - run: ./gradlew shadowJar
