name: Generate README

on:
  push:
    branches:
      - experimental

jobs:
  readme:
    uses: Slimefun5/workflows/.github/workflows/readme-addon.yaml@stable
    with:
      repository: ${{ github.repository }}
