name: Generate README

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  readme:
    permissions:
      contents: write
    uses: Slimefun5/workflows/.github/workflows/readme-addon.yaml@stable
    with:
      repository: ${{ github.repository }}
